# Generated by Django 3.2.8 on 2021-10-16 08:51

from django.db import migrations, models
import django.utils.timezone
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('Đã chuyển đến chuyên viên', 'Đã chuyển đến chuyên viên'), ('Chuyên viên đã xử lý', 'Chuyên viên đã xử lý'), ('Đã chuyển đến giám đốc', 'Đã chuyển đến giám đốc'), ('Giám đốc đã xử lý', 'Giám đốc đã xử lý'), ('Bài post của bạn hợp lệ', 'Bài post của bạn hợp lệ'), ('Bài post của bạn không hợp lệ', 'Bài post của bạn không hợp lệ')], default='Đã chuyển đến chuyên viên', max_length=100)),
                ('upload', models.FileField(blank=True, null=True, upload_to=post.models.file_directory_path)),
                ('is_approve_staff', models.BooleanField(default=False)),
                ('is_approve_director', models.BooleanField(default=False)),
            ],
        ),
    ]
